"use client";

import { useEffect, useRef, useState } from "react";

type Message = { role: "user" | "assistant"; text: string };

// open-ended replies that acknowledge everything and commit to nothing
const replies = [
  "Very interesting. I'll think about it.",
  "Hmm. Let me get back to you on that.",
  "That's a great point. Let's circle back later.",
  "Noted. We'll see where this goes.",
  "I hear you. Definitely something to consider.",
  "Fascinating. Let's revisit this another time.",
  "Good question. I'll look into it.",
  "There's a lot to unpack there.",
  "I see what you mean. Let's keep that in mind.",
  "Understandable. We'll explore that.",
  "Interesting perspective. Worth pondering.",
  "Let me sit with that for a moment.",
  "I'll take that under advisement.",
  "That resonates. Let's keep the conversation open.",
];

export default function Chat() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [thinking, setThinking] = useState(false);
  const endRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, thinking]);

  async function send(e: React.FormEvent) {
    e.preventDefault();
    const text = input.trim();
    if (!text || thinking) return;
    setInput("");
    setMessages((m) => [...m, { role: "user", text }]);
    setThinking(true);
    await new Promise((r) => setTimeout(r, 1200));
    setThinking(false);
    const reply = replies[Math.floor(Math.random() * replies.length)];
    setMessages((m) => [...m, { role: "assistant", text: reply }]);
  }

  return (
    <div className="mx-auto flex min-h-[calc(100vh-9rem)] max-w-2xl flex-col px-6 py-12">
      <a
        href="/"
        className="mb-8 inline-block self-start text-xs tracking-widest text-[#8a8a8a] transition-colors hover:text-[#5a5a5a]"
      >
        ← back to nothing
      </a>

      <div className="mb-8 text-center">
        <span className="rounded-sm border border-[#dcdcdc] px-2 py-0.5 text-[10px] uppercase tracking-widest text-[#8a8a8a]">
          AI-Powered
        </span>
        <h1 className="mt-4 mb-2 text-3xl font-bold tracking-tight text-[#141414]">
          AI Chat Assistant
        </h1>
        <p className="text-sm leading-relaxed text-[#707070]">
          Powered by a state-of-the-art large language model. Ask anything — our neural
          engine processes your message and replies with profound precision.
        </p>
      </div>

      {/* Conversation */}
      <div className="flex-1 space-y-4 overflow-y-auto rounded-xl border border-[#e2e2e0] bg-white p-4">
        {messages.length === 0 && !thinking && (
          <div className="flex h-full min-h-[12rem] items-center justify-center text-center">
            <p className="text-sm text-[#b0b0b0]">Say something. It is listening.</p>
          </div>
        )}

        {messages.map((m, i) => (
          <div key={i} className={`flex ${m.role === "user" ? "justify-end" : "justify-start"}`}>
            <div
              className={`max-w-[80%] rounded-2xl px-4 py-2.5 text-sm leading-relaxed ${
                m.role === "user"
                  ? "bg-[#141414] text-white"
                  : "border border-[#e2e2e0] bg-[#f7f7f5] text-[#141414]"
              }`}
            >
              {m.text}
            </div>
          </div>
        ))}

        {thinking && (
          <div className="flex justify-start">
            <div className="rounded-2xl border border-[#e2e2e0] bg-[#f7f7f5] px-4 py-2.5 text-sm text-[#b0b0b0]">
              <span className="blink">●</span> thinking…
            </div>
          </div>
        )}

        <div ref={endRef} />
      </div>

      {/* Composer */}
      <form onSubmit={send} className="mt-4 flex items-center gap-2">
        <input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Type your message…"
          disabled={thinking}
          className="flex-1 rounded-md border border-[#e2e2e0] bg-white px-4 py-3 text-sm text-[#141414] placeholder-[#b0b0b0] transition-colors focus:border-[#999] focus:outline-none disabled:opacity-50"
        />
        <button
          type="submit"
          disabled={!input.trim() || thinking}
          className="rounded-md bg-[#141414] px-5 py-3 text-sm font-medium uppercase tracking-widest text-white transition-colors hover:bg-black disabled:cursor-not-allowed disabled:opacity-30"
        >
          Send
        </button>
      </form>

      <p className="mt-3 text-center text-[11px] text-[#bbb]">
        Responses are generated by advanced AI and may contain a period.
      </p>
    </div>
  );
}
